[virtualenvs]
in-project = true
create = true

[tool.poetry]
name = "PBG Python Base"
version = "0.0.1"
description = "Materiale del percorso di python base"
authors = ["PBG", "softpython"]
license = "MIT"
homepage = "pythonbiellagroup.it"
repository = "https://github.com/PythonBiellaGroup/PythonBase"
documentation = "pythonbiellagroup.it"

classifiers = [
    "Topic :: Python",
    "Topic :: Base",
    "Topic :: Tutorial",
    "Topic :: Example"
]

[build-system]
requires = ["poetry-core>=1.1.13"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.9, <3.11"

[tool.poetry.dev-dependencies]
flake8 = "^5"
flake8-isort = "^4.0.0"
flake8-builtins = "^1.5.3"
flake8-bandit = "^4"
autopep8 = "^1.5.7"
pylint = "^2.8.2"
bandit = "^1.7.0"
black = "^22"
autoflake = "^1.3.1"
pytest-cov = "^2.8.1"
ipython = "^7.28"
commitizen = "^2.20.0"
jupyter = "^1.0.0"
mypy = "0.982"


# --- ISORT config --------------------------------------------- #
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 120


[tool.pytest.ini_options]
markers = [
    "functions: mark test for the base functionalities",
    "core: all about the core",
    "db: all about the database",
    "api: all about the api of the system",
]


# --- Commitizen Release ----------------------------------------- #
[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$major.$minor.$patch$prerelease"
version = "0.1.0"
version_files = [
    "__version__.py",
    "pyproject.toml:version"
]
style = [
    ["qmark", "fg:#ff9d00 bold"],
    ["question", "bold"],
    ["answer", "fg:#ff9d00 bold"],
    ["pointer", "fg:#ff9d00 bold"],
    ["highlighted", "fg:#ff9d00 bold"],
    ["selected", "fg:#cc5454"],
    ["separator", "fg:#cc5454"],
    ["instruction", ""],
    ["text", ""],
    ["disabled", "fg:#858585 italic"]
]

[[tool.poetry.source]]
name = "pypi.org"
url = "https://pypi.org/simple"
default = true